// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        pgtype.UUID
	PostID    pgtype.UUID
	UserID    pgtype.UUID
	Body      string
	CreatedAt pgtype.Timestamptz
}

type Follow struct {
	ID         pgtype.UUID
	FollowerID pgtype.UUID
	FolloweeID pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

type Like struct {
	ID        pgtype.UUID
	PostID    pgtype.UUID
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Notification struct {
	ID          pgtype.UUID
	RecipientID pgtype.UUID
	ActorID     pgtype.UUID
	Type        string
	PostID      pgtype.UUID
	CommentID   pgtype.UUID
	IsRead      bool
	CreatedAt   pgtype.Timestamptz
}

type Post struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Body      pgtype.Text
	ImageUrl  pgtype.Text
	IsPublic  bool
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID          pgtype.UUID
	Username    string
	Description pgtype.Text
	AvatarUrl   pgtype.Text
	CreatedAt   pgtype.Timestamptz
}
