// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: post.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
insert into posts (id, user_id, body, image_url, is_public, created_at)
values ($1, $2, $3, $4, $5, $6)
returning id, user_id, body, image_url, is_public, created_at
`

type CreatePostParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Body      pgtype.Text
	ImageUrl  pgtype.Text
	IsPublic  bool
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.UserID,
		arg.Body,
		arg.ImageUrl,
		arg.IsPublic,
		arg.CreatedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Body,
		&i.ImageUrl,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const getPostByID = `-- name: GetPostByID :one
select id, user_id, body, image_url, is_public, created_at from posts
where id = $1
`

func (q *Queries) GetPostByID(ctx context.Context, id pgtype.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Body,
		&i.ImageUrl,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}
